name: api_test
description: Projeto teste vaden criação de API's.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.8.0+1
  vaden: ^0.0.8

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.0.8